version: '3'

services:
  db:
    image: postgres:latest
    restart: always

    volumes:
      - ./data/db:/var/lib/postgresql

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: TASKMANAGER
      POSTGRES_USER: VISHALRAGHAV
      POSTGRES_PASSWORD: TASK

  adminer:
    image: adminer
    restart: always

    ports:
      - "8080:8080"


      